### ISSUE TITLE
error: type *Reporter has no field or method runLogProcessor

### ISSUE THREAD

**Issue by netoax** [BGrewell/go-iperf#1]
Hello! How are you?

I found your wrapper very useful for an experiment I'm doing right now. However, I ended up with the following error when trying to install it with the `go get` command:

```
go get github.com/BGrewell/go-iperf
../../../../go/pkg/mod/github.com/!b!grewell/go-iperf@v0.0.0-20210311171621-1dd7340d4bbe/reporter.go:17:6: r.runLogProcessor undefined (type *Reporter has no field or method runLogProcessor)
``` 

Is there any workaround on this?

My environment:
- **Go version**: 1.16 darwin/amd64
- **OS**: macOS - Darwin Kernel Version 18.0.0

The wrapper API is quite simple. Nice job!

**Comment by bgrewell** [comment]
Sorry, I had never actually added macOS support. I think it should work now; I ran it on my macbook running macOS Big Sur and everything works as expected now.

**Comment by bgrewell** [comment]
oops, didn't mean to close it yet. try it out and let me know if you have any issues

**Comment by bgrewell** [comment]
fixed by BGrewell/go-iperf@02dde6c

**Comment by netoax** [comment]
It worked, thank you! 🎉

**Comment by bgrewell** [comment]
Great!
